#!/bin/bash

# Define the GitHub repository URL and the local path for cloning
REPO_URL= "https://github.com/moured/Tesseract-Docker-Service.git"
# "https://accgitlab.access.kit.edu/Maximilian2/Tesseract-OCR-Webservice.git" 
LOCAL_PATH="/home/omoured/Desktop/Tesseract-Docker-Service"

# Define the Docker Compose file path
COMPOSE_FILE="$LOCAL_PATH/docker-compose.yml"

# Monitor the repository for updates and update the service
while true
do
    cd $LOCAL_PATH
    git reset --hard HEAD
    git pull origin main
    if git diff-index --quiet HEAD --; then
        echo "No changes detected in Git repository."
    else
        echo "Changes detected in Git repository, updating container..."
        docker-compose -f $COMPOSE_FILE down
        docker-compose -f $COMPOSE_FILE up -d
    fi
    sleep 5 # 10 minutes
done

